[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "mm"
version = "0.1.0"
description = "Replicating Market Mmaker for bulk exchange API"
requires-python = ">=3.10"
dependencies = [
    #"bulk @ file:///${PROJECT_ROOT}/../bulk",
    "bulk",
    "pandas>=2.3.0",
    "numpy>=2.2.0",
    "numba>=0.60.0",
    "websockets>=14.0",
    "pynacl>=1.2.0",
    "base58>=2.1.0",
    "sortedcontainers>=2.4.0",
    "aiohttp>=3.11",
    "json5>=0.13.0"
]

[project.scripts]
bmm = "mm.bmm.BinanceMM:main"
rmm = "mm.rmm.RandomMM:main"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["mm"]
